-- Ferrova Living CMS schema. Run in Supabase SQL Editor.
create extension if not exists "pgcrypto";
create type content_status as enum ('draft','published','hidden','archived');
create table profiles(id uuid primary key references auth.users on delete cascade, full_name text, role text not null default 'admin', created_at timestamptz default now());
create table pages(id uuid primary key default gen_random_uuid(), title text not null, slug text unique not null, status content_status default 'draft', seo_title text, seo_description text, canonical_url text, og_image text, created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);
create table sections(id uuid primary key default gen_random_uuid(), page_id uuid references pages on delete cascade, type text not null, title text, subtitle text, description text, settings jsonb default '{}', sort_order int default 0, status content_status default 'draft', created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);
create table section_items(id uuid primary key default gen_random_uuid(), section_id uuid references sections on delete cascade, content jsonb default '{}', sort_order int default 0, created_at timestamptz default now());
create table product_categories(id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, description text, sort_order int default 0, deleted_at timestamptz);
create table products(id uuid primary key default gen_random_uuid(), category_id uuid references product_categories, name text not null, slug text unique not null, code text unique, short_description text, description text, specifications jsonb default '{}', price numeric, show_price boolean default false, featured boolean default false, status content_status default 'draft', seo_title text, seo_description text, created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);
create table project_categories(id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, deleted_at timestamptz);
create table projects(id uuid primary key default gen_random_uuid(), category_id uuid references project_categories, title text not null, slug text unique not null, location text, project_type text, description text, completion_date date, featured boolean default false, status content_status default 'draft', seo_title text, seo_description text, created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);
create table media(id uuid primary key default gen_random_uuid(), storage_path text unique not null, url text not null, title text, alt_text text, mime_type text, size_bytes bigint, width int, height int, focal_x numeric default .5, focal_y numeric default .5, created_at timestamptz default now(), deleted_at timestamptz);
create table product_images(id uuid primary key default gen_random_uuid(), product_id uuid references products on delete cascade, media_id uuid references media, sort_order int default 0, is_cover boolean default false, alt_text text);
create table project_images(id uuid primary key default gen_random_uuid(), project_id uuid references projects on delete cascade, media_id uuid references media, sort_order int default 0, is_cover boolean default false, alt_text text);
create table testimonials(id uuid primary key default gen_random_uuid(), name text not null, role text, quote text not null, status content_status default 'draft', sort_order int default 0, deleted_at timestamptz);
create table enquiries(id uuid primary key default gen_random_uuid(), kind text not null, name text not null, email text, phone text, message text, status text default 'new', internal_notes text, created_at timestamptz default now(), deleted_at timestamptz);
create table navigation_items(id uuid primary key default gen_random_uuid(), label text not null, url text not null, location text default 'header', external boolean default false, visible boolean default true, sort_order int default 0, deleted_at timestamptz);
create table website_settings(id int primary key default 1 check(id=1), data jsonb not null default '{}', updated_at timestamptz default now());
create table seo_settings(id int primary key default 1 check(id=1), data jsonb not null default '{}', updated_at timestamptz default now());
create table activity_logs(id bigint generated always as identity primary key, user_id uuid references profiles, action text not null, entity_type text, entity_id uuid, metadata jsonb default '{}', created_at timestamptz default now());
create index sections_page_order on sections(page_id,sort_order); create index products_status on products(status,featured); create index projects_status on projects(status,featured); create index enquiries_status_created on enquiries(status,created_at desc);
alter table profiles enable row level security; alter table pages enable row level security; alter table sections enable row level security; alter table section_items enable row level security; alter table products enable row level security; alter table product_categories enable row level security; alter table projects enable row level security; alter table project_categories enable row level security; alter table media enable row level security; alter table product_images enable row level security; alter table project_images enable row level security; alter table testimonials enable row level security; alter table enquiries enable row level security; alter table navigation_items enable row level security; alter table website_settings enable row level security; alter table seo_settings enable row level security; alter table activity_logs enable row level security;
create function is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles where id=auth.uid() and role='admin') $$;
create policy "public published pages" on pages for select using(status='published' and deleted_at is null or is_admin()); create policy "admins pages" on pages for all using(is_admin()) with check(is_admin());
create policy "public published sections" on sections for select using(status='published' and deleted_at is null or is_admin()); create policy "admins sections" on sections for all using(is_admin()) with check(is_admin());
create policy "public products" on products for select using(status='published' and deleted_at is null or is_admin()); create policy "admins products" on products for all using(is_admin()) with check(is_admin());
create policy "public projects" on projects for select using(status='published' and deleted_at is null or is_admin()); create policy "admins projects" on projects for all using(is_admin()) with check(is_admin());
create policy "submit enquiries" on enquiries for insert to anon with check(length(name) between 2 and 120 and length(message)<=5000); create policy "admins enquiries" on enquiries for all using(is_admin()) with check(is_admin());
-- Apply equivalent public-select/admin-all policies to lookup, media, settings and testimonial tables in production.
insert into website_settings(data) values ('{"brand":"Ferrova Living","tagline":"Crafted for Modern Living","sample":true,"setup_complete":false}');

-- Safe access policies. New accounts are never promoted automatically.
create policy "own profile" on profiles for select using(id=auth.uid() or is_admin()); create policy "admins profiles" on profiles for all using(is_admin()) with check(is_admin());
create policy "public categories" on product_categories for select using(deleted_at is null or is_admin()); create policy "admins product categories" on product_categories for all using(is_admin()) with check(is_admin());
create policy "public project categories" on project_categories for select using(deleted_at is null or is_admin()); create policy "admins project categories" on project_categories for all using(is_admin()) with check(is_admin());
create policy "public testimonials" on testimonials for select using((status='published' and deleted_at is null) or is_admin()); create policy "admins testimonials" on testimonials for all using(is_admin()) with check(is_admin());
create policy "public navigation" on navigation_items for select using((visible and deleted_at is null) or is_admin()); create policy "admins navigation" on navigation_items for all using(is_admin()) with check(is_admin());
create policy "public section items" on section_items for select using(exists(select 1 from sections s where s.id=section_id and s.status='published' and s.deleted_at is null) or is_admin()); create policy "admins section items" on section_items for all using(is_admin()) with check(is_admin());
create policy "public product images" on product_images for select using(exists(select 1 from products p where p.id=product_id and p.status='published' and p.deleted_at is null) or is_admin()); create policy "admins product images" on product_images for all using(is_admin()) with check(is_admin());
create policy "public project images" on project_images for select using(exists(select 1 from projects p where p.id=project_id and p.status='published' and p.deleted_at is null) or is_admin()); create policy "admins project images" on project_images for all using(is_admin()) with check(is_admin());
create policy "public media metadata" on media for select using(deleted_at is null); create policy "admins media" on media for all using(is_admin()) with check(is_admin());
create policy "admins site settings" on website_settings for all using(is_admin()) with check(is_admin()); create policy "admins seo settings" on seo_settings for all using(is_admin()) with check(is_admin());
create policy "admins activity" on activity_logs for select using(is_admin()); create policy "admins log activity" on activity_logs for insert with check(is_admin());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('media','media',true,12582912,array['image/jpeg','image/png','image/webp','image/avif']) on conflict(id) do update set public=true,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "public media reads" on storage.objects for select using(bucket_id='media'); create policy "admin media uploads" on storage.objects for insert with check(bucket_id='media' and is_admin()); create policy "admin media updates" on storage.objects for update using(bucket_id='media' and is_admin()); create policy "admin media deletes" on storage.objects for delete using(bucket_id='media' and is_admin());

-- Create the first auth user in Supabase, then promote only that known user:
-- insert into profiles(id,full_name,role) values('<AUTH-USER-UUID>','Ferrova Administrator','admin');

-- Clearly marked replaceable starter content.
insert into pages(title,slug,status) values('Home','home','published');
insert into product_categories(name,slug,sort_order) values('Lounge Seating','lounge-seating',1),('Dining','dining',2),('Daybeds','daybeds',3),('Sun Loungers','sun-loungers',4),('Tables','tables',5);
insert into products(name,slug,code,short_description,status,featured,specifications) values('Aurelia Lounge Chair','aurelia-lounge-chair','SAMPLE-FL-101','Sample content.','published',true,'{"sample":true}'),('Solace Daybed','solace-daybed','SAMPLE-FL-204','Sample content.','published',true,'{"sample":true}'),('Terra Dining Set','terra-dining-set','SAMPLE-FL-312','Sample content.','published',false,'{"sample":true}'),('Cove Bar Chair','cove-bar-chair','SAMPLE-FL-418','Sample content.','published',false,'{"sample":true}'),('Riva Sun Lounger','riva-sun-lounger','SAMPLE-FL-509','Sample content.','published',true,'{"sample":true}'),('Noma Coffee Table','noma-coffee-table','SAMPLE-FL-611','Sample content.','published',false,'{"sample":true}'),('Mira Dining Chair','mira-dining-chair','SAMPLE-FL-712','Sample content.','published',false,'{"sample":true}'),('Vale Sofa','vale-sofa','SAMPLE-FL-808','Sample content.','published',true,'{"sample":true}');
insert into project_categories(name,slug) values('Hotels and Resorts','hotels-resorts'),('Villas','villas'),('Restaurants and Cafes','restaurants-cafes'),('Poolside Areas','poolside'),('Balconies','balconies'),('Rooftops','rooftops'),('Custom Installations','custom-installations');
insert into projects(title,slug,location,project_type,description,status,featured) values('Aravalli Pool House','aravalli-pool-house','Udaipur','Poolside','Sample project.','published',true),('Desert Courtyard','desert-courtyard','Jaisalmer','Boutique Hotel','Sample project.','published',true),('Lakeview Retreat','lakeview-retreat','Udaipur','Luxury Villa','Sample project.','published',true),('The Rooftop Table','rooftop-table','Jaipur','Restaurant','Sample project.','published',false);
insert into testimonials(name,role,quote,status,sort_order) values('Rhea Kapoor','Principal Architect','Sample testimonial — Ferrova understood the rhythm of our property.','published',1),('Arjun Mehta','Hotelier','Sample testimonial — beautifully made and thoughtfully delivered.','published',2),('Naina Shah','Interior Designer','Sample testimonial — customization was effortless.','published',3);
